import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type { Pool } from 'pg';

/** Hashed by Postgres into the key every instance of the API takes the same lock on. */
const MIGRATION_LOCK_NAME = 'pick-a-book/migrations';

/**
 * Applies the committed migrations (`drizzle/migrations`, generated by `yarn db:generate`).
 *
 * Run by the API at boot, so the schema a revision expects is the schema it gets — locally,
 * in CI and on Cloud Run alike, with no manual step to forget. Cloud Run may start several
 * instances at once: a session-level advisory lock queues them, so the migrations run once
 * and the others find an up-to-date database.
 *
 * The folder is a parameter: where the SQL files sit depends on who runs this — next to the
 * sources for the specs, copied next to the bundle for the API.
 */
export async function migrateDatabase(pool: Pool, migrationsFolder: string): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query('select pg_advisory_lock(hashtext($1))', [MIGRATION_LOCK_NAME]);
    try {
      await migrate(drizzle({ client }), { migrationsFolder });
    } finally {
      await client.query('select pg_advisory_unlock(hashtext($1))', [MIGRATION_LOCK_NAME]);
    }
  } finally {
    client.release();
  }
}
