const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u;

/**
 * Identity of a submitted shelf photo, its scan record and the HTTP resource that exposes
 * them (`/shelf-photos/{id}/scan`) — one id for all three.
 *
 * Generated by the application, never derived from the uploaded file's name: it also names
 * the object in the bucket, and a name supplied by a third party must never get that far
 * (FR-015). Validated on construction because it arrives from a URL path.
 */
export class ShelfScanId {
  private constructor(readonly value: string) {}

  static of(raw: string): ShelfScanId {
    const normalised = raw.toLowerCase();
    if (!UUID.test(normalised)) {
      throw new Error(`ShelfScanId: not a UUID (${raw})`);
    }

    return new ShelfScanId(normalised);
  }

  static generate(): ShelfScanId {
    return new ShelfScanId(crypto.randomUUID());
  }

  equals(other: ShelfScanId): boolean {
    return this.value === other.value;
  }

  toString(): string {
    return this.value;
  }
}
