import type { DetectedBook } from './detected-book.js';
import type { ShelfPhotoMediaType } from './shelf-photo.js';

/**
 * Identifier of a kept scan.
 *
 * Generated by the application (`crypto.randomUUID()`), and the single name under which a
 * submission is known: the object in the bucket, the row in the database and the HTTP
 * resource all answer to it. Never the filename the browser supplied (FR-015).
 */
export type ShelfScanId = string;

/**
 * Where a submission stands.
 *
 * A closed union rather than a nullable list of books: `null` would have to mean both "no
 * result yet" and "the scan failed", and a caller would have no way to tell the two apart.
 */
export type ShelfScanStatus = 'pending' | 'completed' | 'failed';

/** What is known of a submission the moment its photo is stored, before any analysis. */
export interface NewShelfScan {
  readonly id: ShelfScanId;
  readonly ownerId: string;
  readonly photoBucketKey: string;
  readonly photoMediaType: ShelfPhotoMediaType;
  readonly photoSizeBytes: number;
  /**
   * The name the browser gave the file, kept for reference only: it names nothing, routes
   * nothing, and is returned by no endpoint (FR-015).
   */
  readonly originalFilename: string;
}

/**
 * The durable trace of a submitted photo and of what was read from it (US3).
 *
 * Created as `pending` when the photo is stored, then moved exactly once to `completed`
 * (with the books read, empty list included) or `failed`. It never goes back: a scan that
 * answered is not re-run on a whim, which is what keeps a second, accidental call from
 * paying for a VLM that already answered.
 */
export interface ShelfScanRecord extends NewShelfScan {
  readonly status: ShelfScanStatus;
  /** Present exactly when `status` is `completed` — `undefined` while pending, and on failure. */
  readonly detectedBooks: DetectedBook[] | undefined;
  /** When the photo was stored, not when its analysis ended. */
  readonly createdAt: Date;
}

/**
 * Outbound port for keeping scans (ADR 0006).
 *
 * Read and write, not an append-only log: the second HTTP call reads back the record its
 * predecessor created (specs/001-photo-upload/research.md §7). How it is laid out in
 * Postgres — here, two tables joined by the adapter — is invisible from this side (§8).
 *
 * `markCompleted` and `markFailed` refuse a record that has already left `pending`; that
 * refusal is what the 409 of `POST /shelf-photos/{id}/scan` is made of.
 */
export interface ShelfScanRepositoryPort {
  createPending(scan: NewShelfScan): Promise<void>;
  get(id: ShelfScanId): Promise<ShelfScanRecord | undefined>;
  markCompleted(id: ShelfScanId, books: readonly DetectedBook[]): Promise<void>;
  markFailed(id: ShelfScanId): Promise<void>;
}

/** Injection token for the port (see `SHELF_SCANNER_PORT`). */
export const SHELF_SCAN_REPOSITORY_PORT = 'ShelfScanRepositoryPort';
