import { sql } from 'drizzle-orm';
import { check, integer, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Postgres schema of the recognition context (ADR 0006, specs/001-photo-upload research.md §8).
 *
 * Two tables where the domain sees one `ShelfScanRecord`: `uploads` references any file put
 * in the bucket, whatever wrote it, and `shelf_scans` holds the state of the scan of one of
 * them. The split is an infrastructure concern — `DrizzleShelfScanRepositoryAdapter` joins
 * them back, and neither the domain nor the application knows there are two.
 */

/** A detected book as stored in `shelf_scans.detected_books` — plain JSON, no value object. */
export interface StoredDetectedBook {
  readonly author?: string;
  readonly title: string;
  readonly confidence: number;
}

export const uploads = pgTable('uploads', {
  // Generated by the application, and also the name of the object in the bucket.
  id: uuid('id').primaryKey(),
  ownerId: text('owner_id').notNull(),
  // Kind of upload — 'shelf_photo' for everything recognition writes. Text rather than a
  // Postgres enum, so a new kind takes no type migration.
  type: text('type').notNull(),
  bucketKey: text('bucket_key').notNull(),
  mediaType: text('media_type').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  // Reference only: never used to name anything (FR-015).
  originalFilename: text('original_filename').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const shelfScans = pgTable(
  'shelf_scans',
  {
    // Own identity, never exposed: HTTP circulates `upload_id`.
    id: uuid('id').primaryKey().defaultRandom(),
    uploadId: uuid('upload_id')
      .notNull()
      .unique()
      .references(() => uploads.id),
    status: text('status').notNull(),
    detectedBooks: jsonb('detected_books').$type<StoredDetectedBook[]>(),
  },
  (table) => [
    check('shelf_scans_status_check', sql`${table.status} in ('pending', 'completed', 'failed')`),
    // Books exist if and only if the scan completed — the rule of ShelfScanRecord, held by
    // the database too rather than by the adapter alone.
    check(
      'shelf_scans_detected_books_check',
      sql`(${table.status} = 'completed') = (${table.detectedBooks} is not null)`,
    ),
  ],
);
