import { sql } from 'drizzle-orm';
import { integer, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Postgres schema of the recognition context (ADR 0006).
 *
 * SQL, schema and migrations stay in `infrastructure`: `domain` and `application` see a
 * single `ShelfScanRecord`, and know nothing of the two tables it is rebuilt from
 * (specs/001-photo-upload/research.md §8).
 */

/**
 * Every file dropped in the bucket, whichever context wrote it.
 *
 * Generic on purpose: a second kind of upload (an enriched cover for `bibliography`, say)
 * gets a row here rather than another copy of these five columns in its own table. The
 * `type` discriminator is free text rather than a Postgres enum, so a new kind costs no
 * type migration — the same reason `shelf_scans.status` is text.
 */
export const uploads = pgTable('uploads', {
  /** Generated by the application: it names the row, the stored object and the HTTP resource. */
  id: uuid('id').primaryKey(),
  /** Owner segment of `bucketKey`. A fixed value for now, never a real account (research.md §10). */
  ownerId: text('owner_id').notNull(),
  type: text('type').notNull(),
  bucketKey: text('bucket_key').notNull(),
  mediaType: text('media_type').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  /** Reference only: it names nothing that is stored or executed (FR-015). */
  originalFilename: text('original_filename').notNull(),
  /** When the file was stored — canonical for the whole row, `shelf_scans` has no clock of its own. */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/** The `uploads.type` this context writes. */
export const SHELF_PHOTO_UPLOAD_TYPE = 'shelf_photo';

/**
 * The state of the scan carried out on a `shelf_photo` upload, and nothing else.
 *
 * Its own primary key rather than one shared with `uploads`: a scan bears on an upload, it
 * does not stand in for it. `upload_id` is unique — one scan per upload for this feature,
 * enforced by the column rather than left to application discipline.
 *
 * `detected_books` is denormalised: the books read have not been reconciled yet
 * (`bibliography` does not exist), so they have no identity worth a table of their own.
 */
export const shelfScans = pgTable('shelf_scans', {
  id: uuid('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  uploadId: uuid('upload_id')
    .notNull()
    .unique()
    .references(() => uploads.id),
  status: text('status').notNull(),
  detectedBooks: jsonb('detected_books'),
});
