import { sql } from 'drizzle-orm';
import {
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';

/**
 * Postgres schema of the recognition context (ADR 0006, specs/001-photo-upload research.md §8).
 *
 * Two tables where the domain sees one `ShelfScanRecord`: `uploads` references any file put
 * in the bucket, whatever wrote it, and `shelf_scans` holds the state of the scan of one of
 * them. The split is an infrastructure concern — `DrizzleShelfScanRepositoryAdapter` joins
 * them back, and neither the domain nor the application knows there are two.
 *
 * A third table, `scan_attempts`, records each time the scanner was asked about an upload: it
 * is what the daily cap counts and what keeps two scans of one photo from running at once
 * (specs/002-upload-history, research.md §8).
 */

/** A detected book as stored in `shelf_scans.detected_books` — plain JSON, no value object. */
export interface StoredDetectedBook {
  readonly author?: string;
  readonly title: string;
  readonly confidence: number;
}

export const uploads = pgTable(
  'uploads',
  {
    // Generated by the application, and also the name of the object in the bucket.
    id: uuid('id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    // Kind of upload — 'shelf_photo' for what the user sends, 'shelf_photo_thumbnail' for the
    // smaller image the browser makes of it. Text rather than a Postgres enum, so a new kind
    // takes no type migration.
    type: text('type').notNull(),
    bucketKey: text('bucket_key').notNull(),
    mediaType: text('media_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    // Reference only: never used to name anything (FR-015). Null for a derived file, which
    // has no original name — see the check below.
    originalFilename: text('original_filename'),
    // The upload a derived file comes from (a thumbnail points at its photo). One derived
    // file per source: a photo has at most one thumbnail.
    sourceUploadId: uuid('source_upload_id')
      .unique()
      .references((): AnyPgColumn => uploads.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // A file the user sent has a name and no source; a derived file the opposite — held by the
    // database, not only by the adapter.
    check(
      'uploads_source_or_filename_check',
      sql`(${table.sourceUploadId} is null) = (${table.originalFilename} is not null)`,
    ),
    // Serves the history: one owner's photos, newest first, with the id as tie-breaker for the
    // cursor (research.md §4).
    index('uploads_owner_type_created_idx').on(
      table.ownerId,
      table.type,
      table.createdAt.desc(),
      table.id.desc(),
    ),
  ],
);

export const shelfScans = pgTable(
  'shelf_scans',
  {
    // Own identity, never exposed: HTTP circulates `upload_id`.
    id: uuid('id').primaryKey().defaultRandom(),
    uploadId: uuid('upload_id')
      .notNull()
      .unique()
      .references(() => uploads.id),
    status: text('status').notNull(),
    detectedBooks: jsonb('detected_books').$type<StoredDetectedBook[]>(),
  },
  (table) => [
    check('shelf_scans_status_check', sql`${table.status} in ('pending', 'completed', 'failed')`),
    // Books exist if and only if the scan completed — the rule of ShelfScanRecord, held by
    // the database too rather than by the adapter alone.
    check(
      'shelf_scans_detected_books_check',
      sql`(${table.status} = 'completed') = (${table.detectedBooks} is not null)`,
    ),
  ],
);

/**
 * One analysis of an upload, reserved before the scanner is called and closed when it answers
 * (specs/002-upload-history, research.md §8). Counting these — not the results — is what bounds
 * the day's bill: a scan that failed at the provider may have been billed all the same.
 */
export const scanAttempts = pgTable(
  'scan_attempts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    uploadId: uuid('upload_id')
      .notNull()
      .references(() => uploads.id),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    // Null while the analysis runs, or when the instance died before closing it: the lease
    // expires it.
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (table) => [
    // The daily cap counts the attempts since midnight.
    index('scan_attempts_started_at_idx').on(table.startedAt),
    // The lease looks for the one open attempt of an upload.
    index('scan_attempts_open_upload_idx')
      .on(table.uploadId)
      .where(sql`${table.finishedAt} is null`),
  ],
);
